### ISSUE TITLE
New Business Goal is placed.

### ISSUE THREAD

**Issue by jose598** [hvillega99/ISII-WORKSHOPS-API_CENTRO_DE_INVESTIGACION#3] opened 2022-01-18 16:27 UTC
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by hvillega99** [comment] 2022-01-19 20:40
Thanks for request, we have reproduced the issue.

**Comment by hvillega99** [comment] 2022-01-19 20:47
We have categorized the issue.

**Comment by hvillega99** [comment] 2022-01-19 20:58
We have categorized the issue.

**Comment by hvillega99** [comment] 2022-01-19 21:01
will proceed to process the request, @danielon20  will be the assigned analyst and will perform the tests, @carlosqa73  will develop the solution.

**Comment by jose598** [comment] 2022-01-20 00:48
Thank you @hvillega99 I will wait for your response.

**Comment by danielon20** [comment] 2022-01-20 02:02
@jose598 Attached is a document with Impact Analysis report.
We await your approval to start developing the solution.
[Analysis-Report.pdf](https://github.com/hvillega99/ISII-WORKSHOPS-API_CENTRO_DE_INVESTIGACION/files/7901714/Analysis-Report.pdf)

**Comment by jose598** [comment] 2022-01-20 02:38
Hi @danielon20  I'd like to know if you can send me a table with all cases applied, this one is for getting information about how the prima is going to be calculated.

No forget that the request have different cases and discount is applied depend of it.

Thank you!.

**Comment by danielon20** [comment] 2022-01-20 04:31
Hi @jose598, The document now contains a table with all test cases using boundary value approach for tests. 
The new table does not contain test cases for the new requirements because issue is not yet covered.
[Analysis-Report.pdf](https://github.com/hvillega99/ISII-WORKSHOPS-API_CENTRO_DE_INVESTIGACION/files/7902326/Analysis-Report.pdf)

**Comment by jose598** [comment] 2022-01-20 04:58
Hi @danielon20  Ok I got it! 
Hope see these cases/rules later when the issue is over. 

Thank you. 
You can start working on it.

**Comment by carlosqa73** [comment] 2022-01-20 15:29
Hi @jose598, I just included the new business rules in the code.

https://github.com/hvillega99/ISII-WORKSHOPS-API_CENTRO_DE_INVESTIGACION/blob/8fcb13247c7e380a0e4e505e81b9efc744db689e/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L64-L68

**Comment by jose598** [comment] 2022-01-20 17:40
Ok it sounds good! Please send me the test plan with cases/rules applied.

**Comment by danielon20** [comment] 2022-01-21 16:40
Hi @jose598. I already made the table with the new test cases (It is at the end of the document).
I hope you agree to the plan. We wait your answer. 
[Analysis-Report.pdf](https://github.com/hvillega99/ISII-WORKSHOPS-API_CENTRO_DE_INVESTIGACION/files/7915269/Analysis-Report.pdf)

**Comment by jose598** [comment] 2022-01-21 21:50
Yes @danielon20 Everything sounds good. 
I checked the test plan and code on my pc and everything is OK.



Please close the issue.

**Comment by hvillega99** [comment] 2022-01-21 23:44
The solution has been completed and that the programmer @carlosqa73  will release the new software version for you @jose598.

**Comment by jose598** [comment] 2022-01-21 23:49
Thank you @hvillega99

**Comment by carlosqa73** [comment] 2022-01-21 23:51
Hi @jose598! to use the software you can use git or download the zip.

Git: To download the software with git, you can use the **git pull** command.

Once you downloaded the program, you can use eclipse IDE to run it.

**Comment by jose598** [comment] 2022-01-21 23:52
Yes, I already did. 


Thank you

**Comment by hvillega99** [comment] 2022-01-21 23:54
Dear @jose598 , are you satisfied with the solution?

**Comment by jose598** [comment] 2022-01-22 00:04
Yes, thank you @hvillega99

**Comment by hvillega99** [comment] 2022-01-22 00:08
We are glad to work with you, I will proceed to close the issue.

**Closed as completed by hvillega99** 2022-01-22 00:08 UTC
Labels: documentation, enhancement, medium, issue reproduction, issue assigned, impact analysis, issue solved, tests done, tests passed, completeness verification, enactment, follow up
